controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    gripper_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gripper_controller:
      type: position_controllers/GripperActionController

gripper_controller:
  ros__parameters:
    action_monitor_rate: 20.0
    allow_stalling: true
    goal_tolerance: 0.01
    joint: "gripper_finger1_joint"
    max_effort: 0.0
    stall_timeout: 1.0
    stall_velocity_threshold: 0.001

gripper_joint_state_broadcaster:
  ros__parameters:
    interfaces: ["position"]
    joints: ["gripper_finger1_joint"]